### ISSUE TITLE
Still publishing to Docker Hub?

### ISSUE THREAD

**Issue by ensonik** [dockerfile/python#3]
Hi,

My local builds aren't working anymore because the dockerfile images don't seem to be published to Docker Hub anymore.

Can you confirm?

```
Pulling repository dockerfile/python
INFO[0001] Error: image dockerfile/python:latest not found
```

Thanks.

**Comment by stefan-b314** [comment]
Hi,

unfortunately this also seems to be true for all the projects.
Any update on this issue or why dockerfile is not on docker hub anymore?

Thanks!

**Comment by stefan-b314** [comment]
Ahhh... got it: https://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/

**Comment by ensonik** [comment]
Ah. Thanks.
